=== igdimitro/ASP/GuitarShop/App_Data/kitari.dtd
<!ELEMENT guitar_shop (contacts, guitars+, amplifiers+, strings+)>
<!ATTLIST guitar_shop GuitarShopID ID #REQUIRED >
<!ATTLIST guitar_shop name CDATA #REQUIRED >

    <!ELEMENT contacts (adress?, phone, email, website)>
        <!ELEMENT adress (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT website (#PCDATA)>
    <!ELEMENT guitars (guitar+)>    
        <!ELEMENT guitar (acoustic_guitar | electric_guitar)>        
            <!ELEMENT electric_guitar (description, price, body, pickups, pickguard?, tremolo_bar?)>
             <!ATTLIST electric_guitar manufacturer CDATA #REQUIRED>
             <!ATTLIST electric_guitar model CDATA #REQUIRED>
             <!ATTLIST electric_guitar num_strings (6 | 7 | 8 | 9 | 10 | 12) #REQUIRED>
             <!ATTLIST electric_guitar num_frets (21 | 22 | 24) #REQUIRED>
             <!ELEMENT description (#PCDATA)>
             <!ELEMENT price EMPTY>
                <!ATTLIST price value NMTOKEN #REQUIRED>
                <!ATTLIST price currency (BGN | EUR | USD) #REQUIRED>
                <!ELEMENT body (solid_body | hollow_body)>            
                    <!ELEMENT solid_body EMPTY>
                        <!ATTLIST solid_body body_type (Telecaster | Stratocaster | SG | Les_Paul | Jazzmaster | Explorer | Flying_V) #REQUIRED>
                    <!ELEMENT hollow_body EMPTY>
                        <!ATTLIST hollow_body body_type (Fully_Hollow | Thinline_Hollow | Semi_Hollow | Other) #REQUIRED>
                <!ELEMENT pickups (pickup+)>                
                    <!ELEMENT pickup (pickup_type, position)>
                        <!ELEMENT pickup_type (magnetic | piezoelectric | optical) >
                            <!ELEMENT magnetic EMPTY>
                                <!ATTLIST magnetic type (single-coil | humbucker) #REQUIRED>
                            <!ELEMENT piezoelectric EMPTY>
                            <!ELEMENT optical EMPTY>
                        <!ELEMENT position EMPTY>
                            <!ATTLIST position pos (bridge | middle | neck) #REQUIRED>
                <!ELEMENT pickguard (#PCDATA)>
                <!ELEMENT tremolo_bar (#PCDATA)>
            <!ELEMENT acoustic_guitar (classical_guitar | steel-stringed)>
            <!ATTLIST acoustic_guitar electro-acoustic (Yes | No) #REQUIRED>
                <!ELEMENT classical_guitar (price, description)>
                    <!ATTLIST classical_guitar manufacturer CDATA #REQUIRED>
                    <!ATTLIST classical_guitar model CDATA #REQUIRED>
                <!ELEMENT steel-stringed (price, body_type, description)>
                    <!ATTLIST steel-stringed num_strings (6 | 12) #REQUIRED>
                    <!ATTLIST steel-stringed manufacturer CDATA #REQUIRED>
                    <!ATTLIST steel-stringed model CDATA #REQUIRED>
                    <!ELEMENT body_type EMPTY>
                        <!ATTLIST body_type body (Double-oh | Triple-oh | Dreadnought | Jumbo) #REQUIRED >
                        
    <!ELEMENT amplifiers (amplifier+)>
        <!ELEMENT amplifier (price, description, power)>
            <!ATTLIST amplifier manufacturer CDATA #REQUIRED>
            <!ATTLIST amplifier model CDATA #REQUIRED>
            <!ATTLIST amplifier type (vacuum_tube | solid-state | hybrid) #REQUIRED>
            <!ELEMENT power EMPTY>
                <!ATTLIST power value NMTOKEN #REQUIRED>
                <!ATTLIST power unit (Watt | kW | MW) #REQUIRED>
                
    <!ELEMENT strings (acoustic_guitar_strings*, electric_guitar_strings*, classical_guitar_strings*)>
        <!ELEMENT acoustic_guitar_strings (price, description)>
            <!ATTLIST acoustic_guitar_strings manufacturer CDATA #REQUIRED>
            <!ATTLIST acoustic_guitar_strings gauge NMTOKEN #REQUIRED>
        <!ELEMENT electric_guitar_strings (price, description)>   
            <!ATTLIST electric_guitar_strings manufacturer CDATA #REQUIRED>
            <!ATTLIST electric_guitar_strings gauge NMTOKEN #REQUIRED>                
        <!ELEMENT classical_guitar_strings (price, description)>   
            <!ATTLIST classical_guitar_strings manufacturer CDATA #REQUIRED>
            <!ATTLIST classical_guitar_strings gauge NMTOKEN #REQUIRED>

=== igdimitro/ASP/GuitarShop/App_Data/xml_17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS17" name="магазин камертон">
    <contacts>
        <adress>София, ул. Русалка 3</adress>
        <phone>029461726</phone>
        <email>camerton99@abv.bg</email>
        <website>camerton99.com</website>
    </contacts>
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="RGIX28FEQM-BGW" num_strings="8" num_frets="24">
                <description>RG серията е най-разпознаваемата и отличаваща се сред продуктите на Ibanez.
                    Ibanez RGIX28FEQM-BGW е с Gibraltar Standard II-8 бридж и съчетава всички качества на прецизна изработка 
                    на тези инструменти.
                </description>
                <price value="1758" currency="BGN"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="Yes">
                <steel-stringed num_strings="6" manufacturer="Ibanez" model="V72ECE-NT">
                    <price value="363" currency="BGN"/>
                    <body_type body="Double-oh"/>
                    <description>Въпреки, че китарите от V серията са за начинаещи, Ibanez не правят компромиси с качеството на изработка.
                        V72ECE има топ от смърч, тяло и гриф от махагон.
                        Китарата е снабдена с един пиезо-пикъп и AEQ200T предусилвател. 
                        Вградения тунер е страхотно удобство, особено за начинаещите.
                    </description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Career" model="MERRIT-10" type="vacuum_tube">
            <price value="180" currency="BGN"/>
            <description>Усилвателят е идеален за домашни условия. Има вход за китара, вход за слушалки. Има контрол на силата на звука "volume", контрол на високите честоти "treble" и контрол на баса "bass". </description>
            <power value="10" unit="Watt"/>
        </amplifier>
        <amplifier manufacturer="Orange" model="CR35LDX" type="solid-state">
            <price value="450" currency="BGN"/>
            <description>Оранжев  усилвател</description>
            <power value="35" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="KING LION" gauge="0.11">
            <price value="7.99" currency="BGN"/>
            <description>Метални струни за акустична китара. Размери на струните 011-013-021-033-039-048 Струните са от фосфор и бронз. Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="KING LION" gauge="0.9">
            <price value="7.99" currency="BGN"/>
            <description>Струни за електрическа китара KING LION 009-042. Никелови. Изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </electric_guitar_strings>
        <classical_guitar_strings manufacturer="KING LION" gauge="0.27">
            <price value="7.99" currency="BGN"/>
            <description>Найлонови струни за класическа китара. Размерът на струните е .027 .034 .041 .031 .036 .044 Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </classical_guitar_strings>        
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS2" name="Музикален център Икономов">
    <contacts>
        <adress>София, ул. Лавеле 8</adress>
        <phone>0879594460</phone>
        <email>gc@mci-bg.com</email>
        <website>mci-bg.com</website>
    </contacts>    
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Gibson" model="Future Tribute VS" num_strings="6" num_frets="24">
                <description>
                    Произведено в ЮАР.
                </description>
                <price value="1503.83" currency="BGN"/>
                <body>
                    <solid_body body_type="SG"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="GRG150DXB-BKF" num_strings="6" num_frets="24">
                <description>
                   Подобна на GRG150DX, но има тремоло и адаптери от Ibanez.
                </description>
                <price value="578.60" currency="BGN"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="middle"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="No">
                <steel-stringed num_strings="6" manufacturer="Fender" model="F-1030SCE">
                    <price value="1124.22" currency="BGN"/>
                    <body_type body="Dreadnought"/>
                    <description>Няма</description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Marshall" model="DSL40C" type="vacuum_tube">
            <price value="699.99" currency="USD"/>
            <description>
                Лампов усилвател
            </description>
            <power value="40" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="Fender" gauge="0.11">
            <price value="15" currency="BGN"/>
            <description>
                обикновени струни...
            </description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="Dunlop" gauge="0.10">
            <price value="11.39" currency="BGN"/>
            <description>
                струни
            </description>
        </electric_guitar_strings>
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS11" name="Музикален магазин Камертон">
    <contacts>
        <adress>София, ул. цар Симеон 35</adress>
        <phone>029472661</phone>
        <email>camerton94@gmail.com</email>
        <website>camerton94.com</website>
    </contacts>
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Fender" model="Pacific 240CJ" num_strings="6" num_frets="24">
                <description>Няма.</description>               
                <price value="800" currency="USD"/>
                <body>
                    <solid_body body_type="Telecaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>                        
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Yamaha" model="Road Worn Player" num_strings="6" num_frets="22">
                <description>Този тип електрически китари често се свързват с адаптери с една намотка, но към този модел
                    Ямаха добавят още звукова мощ чрез два двунамоткови адаптера плюс добавеното разнообразие от тристепенния
                    ключ, който дава отличен звънтящ звук в средната позиция.</description>
                <price value="530" currency="BGN"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                             <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="middle"/>                        
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="Yes">
                <steel-stringed num_strings="6" manufacturer="Ibanez" model="V72ECE-BK">
                    <price value="360" currency="BGN"/>
                    <body_type body="Double-oh"/>
                    <description>електро-акустична китара</description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Marshall" model="IBZ15GR" type="vacuum_tube">
            <price value="350" currency="BGN"/>
            <description>Лампов усилвател</description>
            <power value="15" unit="Watt"/>
        </amplifier>
        <amplifier manufacturer="Ibanez" model="DSL40C" type="solid-state">
            <price value="699.99" currency="USD"/>
            <description>Няма</description>
            <power value="40" unit="Watt"/>
        </amplifier>
    </amplifiers>    
    <strings>
        <acoustic_guitar_strings manufacturer="Dunlop" gauge="0.11">
            <price value="15" currency="BGN"/>
            <description>
                Внимателната изработка и най-добрите материали ви гарантират добро усещане
                и страхотен звук, комплект след комплект.
            </description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="Fender" gauge="0.10">
            <price value="11.39" currency="BGN"/>
            <description>
                струни
            </description>
        </electric_guitar_strings>
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop  GuitarShopID="GS14" name="Музикален център Петров">
    <contacts>
        <adress>Благоевград, ул. "3-ти март" №15</adress>
        <phone>0899132625</phone>
        <email>sales@mcp-bg.com</email>
        <website>mcp-bg.com</website>
    </contacts>
    <guitars>
        <guitar>
            <acoustic_guitar electro-acoustic="No">
                <classical_guitar manufacturer="Storm" model="CG400 PK">
                    <price value="75" currency="USD"/>
                    <description>
                        Класическа китара 4/4 размер(стандартен). Розов цвят.
                    </description>
                </classical_guitar>
            </acoustic_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="No">
                <steel-stringed num_strings="6" manufacturer="Ibanez" model="V72-BK72">
                    <price value="363" currency="EUR"/>
                    <body_type body="Jumbo"/>
                    <description>Махагонови тяло и гриф</description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="DEAN" model="EVO XM - Black" num_strings="6" num_frets="22">
                <description>Няма</description>
                <price value="720" currency="BGN"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Ibanez" model="TSA15-U" type="hybrid">
            <price value="773" currency="BGN"/>
            <description>Няма</description>
            <power value="25" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings></strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS6" name="музикален магазин">
    <contacts>
        <adress>София, ул. "Коста Лулчев" 52</adress>
        <phone>028705105</phone>
        <email>sky-city@mci-bg.com</email>
        <website>mci-bg.com</website>
    </contacts>    
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="RGIX28FEQM-BGW" num_strings="8" num_frets="24">
                <description>RG серията е най-разпознаваемата и отличаваща се сред продуктите на Ibanez.
                    Ibanez RGIX28FEQM-BGW е с Gibraltar Standard II-8 бридж и съчетава всички качества на прецизна изработка 
                    на тези инструменти.
                </description>
                <price value="1758" currency="BGN"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="RGIX27FEQM-TG" num_strings="7" num_frets="24">
                <description>
                    RG серията е най-разпознаваемата и отличаваща се сред продуктите на Ibanez.
                    Ibanez RGIX27FEQM-TG е с Gibraltar Standard II-7 бридж и съчетава всички качества
                    на прецизна изработка на тези инструменти.
                </description>
                <price value="1562" currency="BGN"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Career" model="MERRIT-10" type="vacuum_tube">
            <price value="180" currency="BGN"/>
            <description>Усилвателят е идеален за домашни условия. Има вход за китара, вход за слушалки. Има контрол на силата на звука "volume", контрол на високите честоти "treble" и контрол на баса "bass". </description>
            <power value="10" unit="Watt"/>
        </amplifier>
        <amplifier manufacturer="Orange" model="CR35LDX" type="solid-state">
            <price value="450" currency="BGN"/>
            <description>Няма</description>
            <power value="35" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="KING LION" gauge="0.11">
            <price value="7.99" currency="BGN"/>
            <description>Метални струни за акустична китара. Размери на струните 011-013-021-033-039-048 Струните са от фосфор и бронз. Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="KING LION" gauge="0.9">
            <price value="7.99" currency="BGN"/>
            <description>Струни за електрическа китара KING LION 009-042. Никелови. Изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </electric_guitar_strings>
        <classical_guitar_strings manufacturer="KING LION" gauge="0.27">
            <price value="7.99" currency="BGN"/>
            <description>Найлонови струни за класическа китара. Размерът на струните е .027 .034 .041 .031 .036 .044 Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </classical_guitar_strings>        
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop  GuitarShopID="GS4" name="музикален център">
    <contacts>
        <adress>Благоевград, ул. "Трети март" №15</adress>
        <phone>0899251326</phone>
        <email>sales@mci-bg.com</email>
        <website>mci-bg.com</website>
    </contacts>
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Yamaha" model="Pacifica 120SJ" num_strings="6" num_frets="22">
                <description>Този тип електрически китари често се свързват с адаптери с една намотка, но към този модел
                    Ямаха добавят още звукова мощ чрез два двунамоткови адаптера плюс добавеното разнообразие от тристепенния
                    ключ, който дава отличен звънтящ звук в средната позиция.
                </description>               
                <price value="400" currency="USD"/>
                <body>
                    <solid_body body_type="Telecaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>                        
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="No">
                <classical_guitar manufacturer="Storm" model="CG400 PK">
                    <price value="125" currency="BGN"/>
                    <description>
                        Класическа китара 4/4 размер(стандартен). Розов цвят.
                    </description>
                </classical_guitar>
            </acoustic_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="Yes">
                <steel-stringed num_strings="6" manufacturer="Ibanez" model="V72ECE-BK">
                    <price value="363" currency="BGN"/>
                    <body_type body="Double-oh"/>
                    <description>Махагонови тяло и гриф</description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="DEAN" model="EVO XM - Black" num_strings="6" num_frets="22">
                <description>Няма</description>
                <price value="320" currency="BGN"/>
                <body>
                    <solid_body body_type="Les_Paul"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Ibanez" model="TSA15-U" type="vacuum_tube">
            <price value="773" currency="BGN"/>
            <description>Няма</description>
            <power value="15" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings></strings>
</guitar_shop>
