=== igdimitro/ASP/GuitarShop/App_Data/kitari.dtd
<!ELEMENT guitar_shop (contacts, guitars+, amplifiers+, strings+)>
<!ATTLIST guitar_shop GuitarShopID ID #REQUIRED >
<!ATTLIST guitar_shop name CDATA #REQUIRED >

    <!ELEMENT contacts (adress?, phone, email, website)>
        <!ELEMENT adress (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT website (#PCDATA)>
    <!ELEMENT guitars (guitar+)>    
        <!ELEMENT guitar (acoustic_guitar | electric_guitar)>        
            <!ELEMENT electric_guitar (description, price, body, pickups, pickguard?, tremolo_bar?)>
             <!ATTLIST electric_guitar manufacturer CDATA #REQUIRED>
             <!ATTLIST electric_guitar model CDATA #REQUIRED>
             <!ATTLIST electric_guitar num_strings (6 | 7 | 8 | 9 | 10 | 12) #REQUIRED>
             <!ATTLIST electric_guitar num_frets (21 | 22 | 24) #REQUIRED>
             <!ELEMENT description (#PCDATA)>
             <!ELEMENT price EMPTY>
                <!ATTLIST price value NMTOKEN #REQUIRED>
                <!ATTLIST price currency (BGN | EUR | USD) #REQUIRED>
                <!ELEMENT body (solid_body | hollow_body)>            
                    <!ELEMENT solid_body EMPTY>
                        <!ATTLIST solid_body body_type (Telecaster | Stratocaster | SG | Les_Paul | Jazzmaster | Explorer | Flying_V) #REQUIRED>
                    <!ELEMENT hollow_body EMPTY>
                        <!ATTLIST hollow_body body_type (Fully_Hollow | Thinline_Hollow | Semi_Hollow | Other) #REQUIRED>
                <!ELEMENT pickups (pickup+)>                
                    <!ELEMENT pickup (pickup_type, position)>
                        <!ELEMENT pickup_type (magnetic | piezoelectric | optical) >
                            <!ELEMENT magnetic EMPTY>
                                <!ATTLIST magnetic type (single-coil | humbucker) #REQUIRED>
                            <!ELEMENT piezoelectric EMPTY>
                            <!ELEMENT optical EMPTY>
                        <!ELEMENT position EMPTY>
                            <!ATTLIST position pos (bridge | middle | neck) #REQUIRED>
                <!ELEMENT pickguard (#PCDATA)>
                <!ELEMENT tremolo_bar (#PCDATA)>
            <!ELEMENT acoustic_guitar (classical_guitar | steel-stringed)>
            <!ATTLIST acoustic_guitar electro-acoustic (Yes | No) #REQUIRED>
                <!ELEMENT classical_guitar (price, description)>
                    <!ATTLIST classical_guitar manufacturer CDATA #REQUIRED>
                    <!ATTLIST classical_guitar model CDATA #REQUIRED>
                <!ELEMENT steel-stringed (price, body_type, description)>
                    <!ATTLIST steel-stringed num_strings (6 | 12) #REQUIRED>
                    <!ATTLIST steel-stringed manufacturer CDATA #REQUIRED>
                    <!ATTLIST steel-stringed model CDATA #REQUIRED>
                    <!ELEMENT body_type EMPTY>
                        <!ATTLIST body_type body (Double-oh | Triple-oh | Dreadnought | Jumbo) #REQUIRED >
                        
    <!ELEMENT amplifiers (amplifier+)>
        <!ELEMENT amplifier (price, description, power)>
            <!ATTLIST amplifier manufacturer CDATA #REQUIRED>
            <!ATTLIST amplifier model CDATA #REQUIRED>
            <!ATTLIST amplifier type (vacuum_tube | solid-state | hybrid) #REQUIRED>
            <!ELEMENT power EMPTY>
                <!ATTLIST power value NMTOKEN #REQUIRED>
                <!ATTLIST power unit (Watt | kW | MW) #REQUIRED>
                
    <!ELEMENT strings (acoustic_guitar_strings*, electric_guitar_strings*, classical_guitar_strings*)>
        <!ELEMENT acoustic_guitar_strings (price, description)>
            <!ATTLIST acoustic_guitar_strings manufacturer CDATA #REQUIRED>
            <!ATTLIST acoustic_guitar_strings gauge NMTOKEN #REQUIRED>
        <!ELEMENT electric_guitar_strings (price, description)>   
            <!ATTLIST electric_guitar_strings manufacturer CDATA #REQUIRED>
            <!ATTLIST electric_guitar_strings gauge NMTOKEN #REQUIRED>                
        <!ELEMENT classical_guitar_strings (price, description)>   
            <!ATTLIST classical_guitar_strings manufacturer CDATA #REQUIRED>
            <!ATTLIST classical_guitar_strings gauge NMTOKEN #REQUIRED>

=== igdimitro/ASP/GuitarShop/App_Data/xml_12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS12" name="Музикален магазин Икономов">
    <contacts>
        <adress>София, ул. Лавеле 25</adress>
        <phone>0874460959</phone>
        <email>gc@mci.com</email>
        <website>mci.bg</website>
    </contacts>    
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Fender" model="Future Tribute" num_strings="7" num_frets="24">
                <description>Произведена в САЩ.</description>
                <price value="800.83" currency="USD"/>
                <body>
                    <solid_body body_type="Jazzmaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="GRG150DXB-BKF" num_strings="6" num_frets="24">
                <description>Подобна на GRG150DX, но има тремоло и адаптери от Ibanez.</description>
                <price value="578.60" currency="BGN"/>
                <body>
                    <solid_body body_type="Telecaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="middle"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
                <tremolo_bar>Да</tremolo_bar>
            </electric_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="Yes">
                <steel-stringed num_strings="6" manufacturer="Fender" model="FSCE130">
                    <price value="524.22" currency="EUR"/>
                    <body_type body="Dreadnought"/>
                    <description>Няма</description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Marshall" model="DSL40C" type="solid-state">
            <price value="699.99" currency="BGN"/>
            <description>усилвател</description>
            <power value="45" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="Fender" gauge="0.12">
            <price value="12.50" currency="BGN"/>
            <description>
                обикновени струни...
            </description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="Dunlop" gauge="0.09">
            <price value="11.39" currency="BGN"/>
            <description>
                струни
            </description>
        </electric_guitar_strings>
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_19.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS19" name="китара БГ">
    <contacts>
        <adress>София, ул. "Коста Лулчев" 52</adress>
        <phone>0899251326</phone>
        <email>sky-city@mci-bg.com</email>
        <website>kitara.bg</website>
    </contacts> 
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Fender" model="Future Tribute VS" num_strings="8" num_frets="24">
                <description>RG серията е най-разпознаваемата и отличаваща се сред продуктите на Ibanez.
                    Ibanez RGIX28FEQM-BGW е с Gibraltar Standard II-8 бридж и съчетава всички качества на прецизна изработка 
                    на тези инструменти.
                </description>
                <price value="540" currency="BGN"/>
                <body>
                    <solid_body body_type="Flying_V"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="middle"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
                <pickguard>Да</pickguard>
                <tremolo_bar>Да</tremolo_bar>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Gibson" model="GRG121DX BKF" num_strings="7" num_frets="22">
                <description>Черен матов цвят</description>
                <price value="1419" currency="USD"/>
                <body>
                    <solid_body body_type="Explorer"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="Yes">
                <steel-stringed num_strings="6" manufacturer="Fender" model="V72ECE-BK">
                    <price value="360" currency="EUR"/>
                    <body_type body="Dreadnought"/>
                    <description>електро-акустична китара</description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Ibanez" model="TSA15-U" type="hybrid">
            <price value="373" currency="EUR"/>
            <description>Няма</description>
            <power value="15" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="Fender" gauge="0.11">
            <price value="7.99" currency="BGN"/>
            <description>Метални струни за акустична китара. Размери на струните 011-013-021-033-039-048 Струните са от фосфор и бронз. Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="Dunlop" gauge="0.9">
            <price value="7.99" currency="BGN"/>
            <description>Струни за електрическа китара KING LION 009-042. Никелови. Изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </electric_guitar_strings>
        <classical_guitar_strings manufacturer="KING" gauge="0.27">
            <price value="7.99" currency="BGN"/>
            <description>Найлонови струни за класическа китара. Размерът на струните е .027 .034 .041 .031 .036 .044 Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </classical_guitar_strings>        
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS10" name="магазин Антифриз">
    <contacts>
        <adress>София, ул. "Коста Лулчев" 52</adress>
        <phone>0899251326</phone>
        <email>sky-city@mci-bg.com</email>
        <website>kitara.bg</website>
    </contacts> 
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Gibson" model="VS" num_strings="6" num_frets="24">
                <description>RG серията е най-разпознаваемата и отличаваща се сред продуктите на Гибсън.
                    Ibanez RGIX28FEQM-BGW е с Gibraltar Standard II-8 бридж и съчетава всички качества на прецизна изработка 
                    на тези инструменти.
                </description>
                <price value="1540" currency="BGN"/>
                <body>
                    <solid_body body_type="Les_Paul"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="GRG121DX" num_strings="8" num_frets="21">
                <description>Черен матов цвят</description>
                <price value="419" currency="BGN"/>
                <body>
                    <solid_body body_type="Flying_V"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
                <pickguard>Да</pickguard>
                <tremolo_bar>Да</tremolo_bar>
            </electric_guitar>
        </guitar>
        <guitar>
            <acoustic_guitar electro-acoustic="No">
                <steel-stringed num_strings="12" manufacturer="Fender" model="V72ECE-12">
                    <price value="1360" currency="BGN"/>
                    <body_type body="Jumbo"/>
                    <description>електро-акустична китара</description>
                </steel-stringed>
            </acoustic_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Behringer" model="BISA150" type="hybrid">
            <price value="1373" currency="BGN"/>
            <description>Няма</description>
            <power value="150" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="Gibson" gauge="0.12">
            <price value="7.99" currency="BGN"/>
            <description>Метални струни за акустична китара. Размери на струните 012-014-021-033-039-048 Струните са от фосфор и бронз. Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="Bunlod" gauge="0.9">
            <price value="10.99" currency="BGN"/>
            <description>Струни за електрическа китара Bunlod 009-042. Никелови. Изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </electric_guitar_strings>
        <classical_guitar_strings manufacturer="LION" gauge="0.27">
            <price value="12.99" currency="BGN"/>
            <description>Найлонови струни за класическа китара. Размерът на струните е .027 .034 .041 .031 .036 .044 Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </classical_guitar_strings>        
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS3" name="магазин">
    <contacts>
        <adress>София, ул. "Коста Лулчев" 52</adress>
        <phone>028705105</phone>
        <email>sky-city@mci-bg.com</email>
        <website>mci-bg.com</website>
    </contacts>    
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Yamaha" model="Pacifica PAC112V" num_strings="6" num_frets="22">
                <description>
                    Тяло от елша, кленов гриф, доживотна гаранция от Ямаха. Разполага с пет степенен ключ за адаптерите. Два потенциометъра(за сила на звука и тон).
                </description>
                <price value="455" currency="USD"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="middle"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Career" model="HSS-2000 Black" num_strings="6" num_frets="22">
                <description>
                    Евтина електрическа китара с добро качество.
                </description>
                <price value="84.99" currency="EUR"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="single-coil"/>
                        </pickup_type>
                        <position pos="middle"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Кремона" model="Фиеста FS" num_strings="12" num_frets="21">
                <description>Произведена в Казанлък.</description>
                <price value="1200" currency="BGN"/>
                <body>
                    <hollow_body body_type="Fully_Hollow"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Kenwood" model="A-5X" type="hybrid">
            <price value="200" currency="BGN"/>
            <description>
                Втора употреба.
            </description>
            <power value="100" unit="Watt"/>
        </amplifier>
        <amplifier manufacturer="Storm" model="AB-10" type="vacuum_tube">
            <price value="99" currency="BGN"/>
            <description>Усилвателят е идеален за домашни условия. Има вход за китара, вход за слушалки. Има контрол на силата на звука "volume", контрол на високите честоти "treble" и контрол на баса "bass". </description>
            <power value="10" unit="Watt"/>
        </amplifier>
        <amplifier manufacturer="Orange" model="CR35LDX" type="solid-state">
            <price value="450" currency="BGN"/>
            <description>Няма</description>
            <power value="35" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="KING LION" gauge="0.11">
            <price value="7.99" currency="BGN"/>
            <description>Метални струни за акустична китара. Размери на струните 011-013-021-033-039-048 Струните са от фосфор и бронз. Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="KING LION" gauge="0.9">
            <price value="7.99" currency="BGN"/>
            <description>Струни за електрическа китара KING LION 009-042. Никелови. Изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </electric_guitar_strings>
        <classical_guitar_strings manufacturer="KING LION" gauge="0.27">
            <price value="7.99" currency="BGN"/>
            <description>Найлонови струни за класическа китара. Размерът на струните е .027 .034 .041 .031 .036 .044 Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </classical_guitar_strings>        
    </strings>
</guitar_shop>

=== igdimitro/ASP/GuitarShop/App_Data/xml_15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guitar_shop SYSTEM "file:/C:\Users\lenovo\Documents\Visual Studio 2012\Projects\GuitarShop\GuitarShop\App_Data\kitari.dtd">
<guitar_shop GuitarShopID="GS15" name="китара.бг">
    <contacts>
        <adress>София, Младост 1А, ул. д-р София Аврамова 3</adress>
        <phone>0876919296</phone>
        <email>magazin@kitara.bg</email>
        <website>kitara.bg</website>
    </contacts>
    <guitars>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="GRG121DX BKF" num_strings="6" num_frets="24">
                <description>Черен матов цвят</description>
                <price value="419" currency="BGN"/>
                <body>
                    <solid_body body_type="Stratocaster"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
        <guitar>
            <electric_guitar manufacturer="Ibanez" model="XP300FX-BK" num_strings="6" num_frets="24">
                <description>Махагоново тяло, кленов гриф.</description>
                <price value="603" currency="BGN"/>
                <body>
                    <solid_body body_type="Explorer"/>
                </body>
                <pickups>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="neck"/>
                    </pickup>
                    <pickup>
                        <pickup_type>
                            <magnetic type="humbucker"/>
                        </pickup_type>
                        <position pos="bridge"/>
                    </pickup>
                </pickups>
            </electric_guitar>
        </guitar>
    </guitars>
    <amplifiers>
        <amplifier manufacturer="Ibanez" model="TSA15-U" type="vacuum_tube">
            <price value="773" currency="BGN"/>
            <description>Няма</description>
            <power value="15" unit="Watt"/>
        </amplifier>
    </amplifiers>
    <strings>
        <acoustic_guitar_strings manufacturer="KING LION" gauge="0.11">
            <price value="7.99" currency="BGN"/>
            <description>Метални струни за акустична китара. Размери на струните 011-013-021-033-039-048 Струните са от фосфор и бронз. Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </acoustic_guitar_strings>
        <electric_guitar_strings manufacturer="KING LION" gauge="0.9">
            <price value="7.99" currency="BGN"/>
            <description>Струни за електрическа китара KING LION 009-042. Никелови. Изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </electric_guitar_strings>
        <classical_guitar_strings manufacturer="KING LION" gauge="0.27">
            <price value="7.99" currency="BGN"/>
            <description>Найлонови струни за класическа китара. Размерът на струните е .027 .034 .041 .031 .036 .044 Струните са изработени по специална технология. Характеризират се с приятен тембър, добро звучене, издръжливост. Струните KING LION са харесвани от много музиканти.</description>
        </classical_guitar_strings>
        
    </strings>
</guitar_shop>
